kind: config
spec:
  agent_options:
    config:
      decorators:
        load:
          - SELECT uuid AS host_uuid FROM system_info;
          - SELECT hostname AS hostname FROM system_info;
      options:
        disable_distributed: false
        distributed_interval: 10
        distributed_plugin: tls
        distributed_tls_max_attempts: 3
        logger_tls_endpoint: /api/osquery/log
        logger_tls_period: 10
        pack_delimiter: /
  labels:
    - ./lib/labels/is-windows.yml
    - ./lib/labels/is-linux.yml
    - ./lib/labels/is-macos.yml
  policies:
  - name: Check VPN Win
    platform: windows
    query: |
      SELECT interface FROM interface_details WHERE interface LIKE '%vpn%' AND interface NOT LIKE '%Tailscale%';
    description: Проверка VPN интерфейсов
    resolution: Убедитесь, что используется корректный VPN клиент
  org_info:
    org_name: Fleet
    org_logo_url: https://fleetdm.com/logo.png
    contact_url: https://fleetdm.com/company/contact
  fleet_desktop:
    transparency_url: https://fleetdm.com/transparency
  server_settings:
    server_url: http://fleetdm.example.com
    enable_analytics: true
    ai_features_disabled: true
    deferred_save_host: false
    live_query_disabled: false
    query_report_cap: 0
    query_reports_disabled: false
    scripts_disabled: false
  host_expiry_settings:
    host_expiry_enabled: false
    host_expiry_window: 0
  features:
    enable_software_inventory: true
    enable_host_users: true
  webhook_settings:
    interval: 24h0m0s
    vulnerabilities_webhook:
      enable_vulnerabilities_webhook: true
      destination_url: https:/tese.fleetdm.com
      host_batch_size: 0
